services:
  light-service-1:
    build:
      context: ./light-service
      dockerfile: Dockerfile.dev
    environment:
      PORT: "3001"
      HOST: "0.0.0.0"
    volumes:
      - ./light-service:/app
      - /app/node_modules

  light-service-2:
    build:
      context: ./light-service
      dockerfile: Dockerfile.dev
    environment:
      PORT: "3002"
      HOST: "0.0.0.0"
    volumes:
      - ./light-service:/app
      - /app/node_modules

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    depends_on:
      - light-service-1
      - light-service-2
